### ISSUE TITLE
デプロイ時のマイグレーション実行でエラー

### ISSUE THREAD

**Issue by taniwhy** [taniwhy/blog#12]
```
15:06:44 INFO: Environment update is starting.
15:07:27 INFO: Deploying new version to instance(s).
15:07:33 INFO: Environment health has transitioned from Ok to Info. Application update in progress (running for 6 seconds).
15:07:37 INFO: Still updating, status is "Updating", health is "Green", health status is "Info"
15:07:37 ERROR: Instance deployment failed. For details, see 'eb-engine.log'.
15:07:39 ERROR: [Instance: i-01[32](https://github.com/taniwhy/blog/actions/runs/3541735232/jobs/5946377239#step:6:33)c4cad5c309f85] Command failed on instance. Return code: 1 Output: Engine execution has encountered an error..
15:07:39 INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
15:07:39 ERROR: Unsuccessful command execution on instance id(s) 'i-0132c4cad5c309f85'. Aborting the operation.
15:07:[39](https://github.com/taniwhy/blog/actions/runs/3541735232/jobs/5946377239#step:6:40) ERROR: Failed to deploy application.
15:07:39 ERROR: During an aborted deployment, some instances may have deployed the new application version. To ensure all instances are running the same version, re-deploy the appropriate application version.
15:07:48 ERROR: Deployment failed! Current State: Version: batch-ver-2022-11-24T13:10:53.746Z, Health: Red, Health Status: Degraded
Error: Deployment failed: Error: Deployment failed! Current State: Version: batch-ver-2022-11-24T13:10:53.746Z, Health: Red, Health Status: Degraded
```

**Comment by taniwhy** [comment]
```
2022-11-24 15:07:37,434 [ERROR] Command migration (cd /var/app/current
bin/cake migrations migrate
) failed
2022-11-24 15:07:37,434 [ERROR] Error encountered during build of postbuild_0_my_blog: Command migration failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 576, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 276, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command migration failed
2022-11-24 15:07:37,435 [ERROR] -----------------------BUILD FAILED!------------------------
2022-11-24 15:07:37,435 [ERROR] Unhandled exception during build: Command migration failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 137, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 564, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 576, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 276, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command migration failed
```

**Comment by taniwhy** [comment]
原因として以下が考えられる。

- デプロイ完了する前のアプリケーションは`/var/app/current`ではなく、`/var/app/staging`に配置されるため
- app_local.php でDB接続情報が上書きされているため

**Comment by taniwhy** [comment]
エラー解消されないため、しばらくトライアンドエラーしてみる。

**Comment by taniwhy** [comment]
少し雑な対応になっているため、今後整理する。
